CREATE TABLE dbmovies (
    id NUMBER(38,0) NOT NULL,
    buget NUMBER(38,0),
    gen VARCHAR2(230 BYTE),
    pagina VARCHAR2(138 BYTE),
    cuv_cheie VARCHAR2(3783 BYTE),
    limba VARCHAR2(2 BYTE),
	titlu VARCHAR2(86 BYTE) NOT NULL,
    overview VARCHAR2(1000 BYTE),
    popularitate NUMBER(38, 6),
    companii_producatoare VARCHAR2(1155 BYTE),
    tari_producatoare VARCHAR2(517 BYTE),
    data_lansare DATE,
    profit NUMBER(38,0),
    durata NUMBER(38,0),
    limbi_vorbite VARCHAR2(474 BYTE),
    status VARCHAR2(15 BYTE),
    tagline VARCHAR2(252 BYTE),
    title VARCHAR2(86 BYTE) NOT NULL,
    medie_vot NUMBER(38, 1) NOT NULL,
    numar_voturi NUMBER(38,0) NOT NULL,
);
